# Generated by Django 3.1.3 on 2021-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='main', max_length=200),
            preserve_default=False,
        ),
    ]
